// -------------------------------------------------------------
// 
// File Name: D:\class\ECE\ECE260C\2022\Canvas\Lab Material\lab2 -- adpcm\hdl_proj_round_trip\hdlsrc\adpcm_rtl_min\Subsystem_tb.v
// Created: 2022-04-07 18:07:32
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1e-05
// Target subsystem base rate: 1e-05
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1e-05
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1                          ce_out        1e-05
// Out2                          ce_out        1e-05
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_tb
// Source Path: 
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

class Packet;
  rand bit [4:0]  change;
endclass

module Subsystem_tb;

  logic               clk = 'b0,
                      reset = 'b1,
                      enable = 'b0;

    logic  signed[15:0] in1=0;

    logic  signed[15:0] Out1;
    logic  signed[3:0] Out2;
    logic             ce_out;


  always begin
    #5ns clk = 'b1;
    #5ns clk = 'b0;
  end


  initial begin
    automatic Packet pkt = new();
    #20ns reset = 'b0;
    enable = 'b1;
    for(int i=0; i<60; i++) begin
      #10ns 
      pkt.randomize();
      in1 = in1 + pkt.change;
    end
    #20ns $stop;
  end
  
  
  

  Subsystem u_Subsystem (.clk(clk),
                         .reset_x(reset),
                         .clk_enable(enable),
                         .in1(in1),  // sfix20_En16
                         .ce_out(ce_out),
                         .Out1(Out1),  // sfix20_En16
                         .Out2(Out2)  // sfix2
                         );

endmodule  // Subsystem_tb

